//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resturant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_beefsteak_food_restaurant_meat_t_bone_steak_beef_roast_beef {
            get {
                object obj = ResourceManager.GetObject("png-clipart-beefsteak-food-restaurant-meat-t-bone-steak-beef-roast-beef", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_bowl_of_vegetable_salad_greek_salad_vinaigrette_caesar_salad_fruit_salad_salad_leaf_vegetable_food {
            get {
                object obj = ResourceManager.GetObject("png-clipart-bowl-of-vegetable-salad-greek-salad-vinaigrette-caesar-salad-fruit-sa" +
                        "lad-salad-leaf-vegetable-food", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_cheeseburger_hamburger_chicken_sandwich_fast_food_samosa_beef_burger_food_beef {
            get {
                object obj = ResourceManager.GetObject("png-clipart-cheeseburger-hamburger-chicken-sandwich-fast-food-samosa-beef-burger-" +
                        "food-beef", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_chocolate_beverage_coffee_ganache_hot_chocolate_chocolate_pudding_coffee_splash_color_splash_food {
            get {
                object obj = ResourceManager.GetObject("png-clipart-chocolate-beverage-coffee-ganache-hot-chocolate-chocolate-pudding-cof" +
                        "fee-splash-color-splash-food", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_chocolate_ice_cream_frappe_coffee_milkshake_iced_coffee_iced_coffee_food_frozen_dessert {
            get {
                object obj = ResourceManager.GetObject("png-clipart-chocolate-ice-cream-frappe-coffee-milkshake-iced-coffee-iced-coffee-f" +
                        "ood-frozen-dessert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_coca_cola_coca_cola_coke {
            get {
                object obj = ResourceManager.GetObject("png-clipart-coca-cola-coca-cola-coke", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_espresso_martini_cocktail_kahlua_espresso_martini_glass_cocktail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-espresso-martini-cocktail-kahlua-espresso-martini-glass-cocktail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_fries_illustration_french_fries_deep_fryer_partypizza_potato_hand_painted_potato_chips_watercolor_painting_hand {
            get {
                object obj = ResourceManager.GetObject("png-clipart-fries-illustration-french-fries-deep-fryer-partypizza-potato-hand-pai" +
                        "nted-potato-chips-watercolor-painting-hand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_green_tea_bubble_tea_mate_assam_tea_tea_food_tea {
            get {
                object obj = ResourceManager.GetObject("png-clipart-green-tea-bubble-tea-mate-assam-tea-tea-food-tea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_lasagne_pizza_bolognese_sauce_bechamel_sauce_prosciutto_pizza_food_beef {
            get {
                object obj = ResourceManager.GetObject("png-clipart-lasagne-pizza-bolognese-sauce-bechamel-sauce-prosciutto-pizza-food-be" +
                        "ef", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_latte_espresso_milk_iced_coffee_ice_cream_milk_cream_cafe {
            get {
                object obj = ResourceManager.GetObject("png-clipart-latte-espresso-milk-iced-coffee-ice-cream-milk-cream-cafe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_medium_rare_steak_on_chopping_board_beefsteak_barbecue_rib_eye_steak_recipe_western_steak_food_beef {
            get {
                object obj = ResourceManager.GetObject("png-clipart-medium-rare-steak-on-chopping-board-beefsteak-barbecue-rib-eye-steak-" +
                        "recipe-western-steak-food-beef", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_orange_juice_valencia_orange_tequila_sunrise_shop_goods_food_orange {
            get {
                object obj = ResourceManager.GetObject("png-clipart-orange-juice-valencia-orange-tequila-sunrise-shop-goods-food-orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_pizza_hut_italian_cuisine_take_out_restaurant_pizza_pizza_pie_food_pizza_logo {
            get {
                object obj = ResourceManager.GetObject("png-clipart-pizza-hut-italian-cuisine-take-out-restaurant-pizza-pizza-pie-food-pi" +
                        "zza-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_potato_chips_potato_chips {
            get {
                object obj = ResourceManager.GetObject("png-clipart-potato-chips-potato-chips", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_roasted_chicken_and_vegetables_dish_tandoori_chicken_roast_chicken_barbecue_chicken_fried_chicken_tasty_roast_chicken_food_animals {
            get {
                object obj = ResourceManager.GetObject("png-clipart-roasted-chicken-and-vegetables-dish-tandoori-chicken-roast-chicken-ba" +
                        "rbecue-chicken-fried-chicken-tasty-roast-chicken-food-animals", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_salad_bar_pasta_salad_egg_salad_greek_salad_salad_vegetable_salad_in_nowl_leaf_vegetable_food {
            get {
                object obj = ResourceManager.GetObject("png-clipart-salad-bar-pasta-salad-egg-salad-greek-salad-salad-vegetable-salad-in-" +
                        "nowl-leaf-vegetable-food", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_two_grilled_patties_art_hamburger_mcdonald_s_quarter_pounder_barbecue_patty_meat_beef_burger_food_beef {
            get {
                object obj = ResourceManager.GetObject("png-clipart-two-grilled-patties-art-hamburger-mcdonald-s-quarter-pounder-barbecue" +
                        "-patty-meat-beef-burger-food-beef", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cashier_restaurant_support_png_image_11665978 {
            get {
                object obj = ResourceManager.GetObject("pngtree-cashier-restaurant-support-png-image_11665978", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cashier_restaurant_support_png_image_116659781 {
            get {
                object obj = ResourceManager.GetObject("pngtree-cashier-restaurant-support-png-image_116659781", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
